=== XaquinAlves/XML/examenDTD/Xaquin_Alves_exameDTD1.dtd
<!ELEMENT facturas (factura)*>
    <!ELEMENT factura (data,lineaFactura+,cliente,totalFactura)>
        <!ATTLIST factura numFactura ID #REQUIRED>
        <!ELEMENT data (#PCDATA)>
        <!ELEMENT totalFactura (#PCDATA)>
        <!ELEMENT cliente EMPTY>
            <!ATTLIST cliente nome CDATA #REQUIRED>
            <!ATTLIST cliente email CDATA #IMPLIED>
        <!ELEMENT lineaFactura (producto,cantidade,precio,total)>
            <!ELEMENT producto (#PCDATA)>
            <!ELEMENT cantidade (#PCDATA)>
            <!ELEMENT precio (#PCDATA)>
            <!ELEMENT total (#PCDATA)>

=== XaquinAlves/XML/examenDTD/Xaquin_Alves_exameDTD1.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "Xaquin_Alves_exameDTD1.dtd">
<facturas>
    <factura numFactura="A00003401">
        <data>01/01/2019</data>
        <lineaFactura>
            <producto>Document1</producto>
            <cantidade>1</cantidade>
            <precio>100</precio>
            <total>100</total>
        </lineaFactura>
        <lineaFactura>
            <producto>Document2</producto>
            <cantidade>1</cantidade>
            <precio>50</precio>
            <total>50</total>
        </lineaFactura>
        <lineaFactura>
            <producto>Document3</producto>
            <cantidade>2</cantidade>
            <precio>50</precio>
            <total>100</total>
        </lineaFactura>
        <lineaFactura>
            <producto>Document4</producto>
            <cantidade>1</cantidade>
            <precio>100</precio>
            <total>100</total>
        </lineaFactura>
        <cliente nome="John Smith" email="jh@email.com" />
        <totalFactura>350</totalFactura>
    </factura>
</facturas>
