=== XaquinAlves/XML/Tema2.SCHEMAS/Tarefa4/tarefa4.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="titulo" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="editorial" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== XaquinAlves/XML/SCHEMASTema2/Tarefa4/tarefa4.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tarefa4.xsd">
    <libro>
        <titulo>El Hobbit</titulo>
        <editorial>minutauro</editorial>
        <autor>J.R.R. Tolkien</autor>
    </libro>
    <libro>
        <autor>F. Iba√±ez</autor>
        <titulo>Rompetechos</titulo>
        <editorial>Anaya</editorial>
    </libro>
    <libro>
        <editorial>Booket</editorial>
        <autor>Dmitry Glukhovsky</autor>
        <titulo>Metro 2033</titulo>
    </libro>
</biblioteca>
