=== XaquinAlves/XML/Tema2.DTD/proba2.dtd
<!ELEMENT aviso (titulo?, (parrafo+, grafico)*, (comentario|resumo))>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT parrafo (#PCDATA)>
    <!ELEMENT grafico (#PCDATA)>
    <!ELEMENT comentario (#PCDATA)>
    <!ELEMENT resumo (#PCDATA)>

=== XaquinAlves/XML/DTDTema2/proba2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aviso SYSTEM "proba2.dtd">
<aviso>
    <titulo></titulo>

    <parrafo></parrafo>
    <parrafo></parrafo>
    <grafico></grafico>

    <parrafo></parrafo>
    <grafico></grafico>

    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <grafico></grafico>

    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <parrafo></parrafo>
    <grafico></grafico>

    <comentario></comentario>
</aviso>
