=== XaquinAlves/XML/SCHEMASTema2/proba1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mensaxesTexto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mensaxe" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numTlf" type="xs:string"></xs:element>
                            <xs:element name="dataEnvio" type="xs:date"></xs:element>
                            <xs:element name="horaEnvio" type="xs:time"></xs:element>
                            <xs:element name="contido" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== XaquinAlves/XML/SCHEMASTema2/proba1.xml
<?xml version="1.0" encoding="UTF-8"?>

<mensaxesTexto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="proba1.xsd">
    <mensaxe>
        <numTlf>666 666 666</numTlf>
        <dataEnvio>1999-03-31</dataEnvio>
        <horaEnvio>12:30:00</horaEnvio>
        <contido>Hola</contido>
    </mensaxe>
    <mensaxe>
        <numTlf>677 777 777</numTlf>
        <dataEnvio>2002-01-31</dataEnvio>
        <horaEnvio>09:00:00</horaEnvio>
        <contido>Que tal</contido>
    </mensaxe>
    <mensaxe>
        <numTlf>666 666 666</numTlf>
        <dataEnvio>2002-12-31</dataEnvio>
        <horaEnvio>14:23:35</horaEnvio>
        <contido>Feliciano</contido>
    </mensaxe>
</mensaxesTexto>
