=== XaquinAlves/XML/Tema2.SCHEMAS/Tarefa9/tarefa9.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="isbn" type="xs:NMTOKEN" />
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="autor" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="ref" type="xs:ID" use="required"></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="author-ref">
                                <!--Referencias
                                a otros autores-->
                                <xs:complexType>
                                    <xs:attribute name="ref"
                                        type="xs:IDREF" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <!--Elemento
                        clave cuyo contenido no se puede repetir-->
                        <xs:attribute name="identifier"
                            type="xs:ID" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== XaquinAlves/XML/SCHEMASTema2/Tarefa9/tarefa9.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tarefa9.xsd">
    <book identifier="a123">
        <isbn>8423366480</isbn>
        <title>Las que no duermen</title>
        <autor ref="a1">Dolores redondo</autor>
        <author-ref ref="a1" />
    </book>
    <book identifier="b456">
        <isbn>8408294466</isbn>
        <title>545 recetas para triunfar</title>
        <autor ref="a2">Karlos Arguiñano</autor>
        <author-ref ref="a2" />
    </book>
    <book identifier="c789">
        <isbn>8410299631</isbn>
        <title>La isla de la Mujer Dormida</title>
        <autor ref="a3">Arturo Perez Reverte</autor>
        <author-ref ref="a3" />
    </book>
    <book identifier="d123">
        <isbn>8408264370</isbn>
        <title>Cocina fácil y rico: Más de 600 recetas para triunfar</title>
        <author-ref ref="a2" />
    </book>

</library>
