=== XaquinAlves/XML/Tema2.SCHEMAS/Tarefa2/tarefa2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="alumnos" type="tipoAlumnos" />

    <xs:complexType name="tipoAlumnos">
        <xs:sequence>
            <xs:element name="alumno" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1" />
                        <xs:element name="direccion" minOccurs="1" maxOccurs="2">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="ciudad" type="xs:string" use="required"></xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>

                            </xs:complexType>
                        </xs:element>
                        <xs:element name="telefono" type="xs:integer" minOccurs="1" maxOccurs="3" />
                    </xs:sequence>
                    <xs:attribute name="IES" type="xs:string"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== XaquinAlves/XML/Tema2.SCHEMAS/Tarefa2/tarefa2.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tarefa2.xsd">
    <alumno IES="Pazo da Merce">
        <nombre>Pepe</nombre>
        <direccion ciudad="Vigo">Calle falsa 123</direccion>
        <direccion ciudad="Pontevedra">Calle falsa 456</direccion>
        <telefono>666671366</telefono>
    </alumno>
    <alumno IES="Salvaterra de MiÃ±o">
        <nombre>Manuel</nombre>
        <direccion ciudad="Vigo">Calle verdadera 987</direccion>
        <telefono>655555555</telefono>
        <telefono>677777777</telefono>
    </alumno>
</alumnos>
